### ISSUE TITLE
Exposed credentials

### ISSUE THREAD

**Issue by zeroby0** [zense/sac_elections_2020#19]
There are exposed credentials in:
- https://github.com/zense/sac_elections_2020/blob/master/sac_election.env
- https://github.com/zense/sac_elections_2020/blob/master/dbcreation.sql
- https://github.com/zense/sac_elections_2020/blob/master/sac_elections/oauth_settings.yml
- https://github.com/zense/sac_elections_2020/blob/master/sac_elections/sac_elections/settings.py.example
- https://github.com/zense/sac_elections_2020/tree/master/db

Some of these may not be critical as the elections have passed, but patterns can be drawn from available credentials and tested against other Zense projects. For instance, [devPass123](https://github.com/zense/sac_elections_2020/blob/master/dbcreation.sql#L4). Additionally, if this repo is used for elections again next year, credentials could be accidentally re-used. 

If you must store credentials along with code, save them as ENV variables in a file and encrypt the file before committing with githooks. Or even better, use [git-secret.io](https://git-secret.io/).

**Comment by gr455** [comment]
@zeroby0 Thanks a lot for reporting this. But no need to worry all the credentials in the files are for development purposes only. For instance 'devPass123'. We have seperate settings.py, d-c.yml for the server which takes these credentials from the env.

The credentials in oauth_settings.py had beed destroyed(on Azure side) before making this repository public. And dbcreation.sql is a dead file from out initial plan of using MySQL.

**Comment by zeroby0** [comment]
That's reassuring. Good job :)
